// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Catalog: typeof import('./components/catalog/catalog.vue')['default']
    Edit: typeof import('./components/toolbar/idea/edit.vue')['default']
    Highlight: typeof import('./components/highlight/highlight.vue')['default']
    Idea: typeof import('./components/idea/idea.vue')['default']
    Input: typeof import('./components/toolbar/idea/input.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NImage: typeof import('naive-ui')['NImage']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    Notes: typeof import('./components/notes/notes.vue')['default']
    NProgress: typeof import('naive-ui')['NProgress']
    NResult: typeof import('naive-ui')['NResult']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./components/toolbar/toolbar.vue')['default']
  }
}
